In [1]:
import pandas as pd
articles_metadata=pd.read_csv(r'.\data\articles.csv')
customers_metadata=pd.read_csv(r'.\data\customers.csv')
transactions_train30000=pd.read_csv(r'.\data\transactions_train30000.csv')

In [2]:
def combine_customers_data_and_article_ID_1element(article_id_list,customers_metadata,i):
    customers_metadata_element=customers_metadata.copy()
    customers_metadata_element['article_id']=article_id_list[i]
    return customers_metadata_element
article_id_list=articles_metadata['article_id'].to_list()

In [3]:
df=combine_customers_data_and_article_ID_1element(article_id_list,customers_metadata,0)

In [4]:
for i in range(len(article_id_list)-1):
    print('{}/{}'.format(i,len(article_id_list)))
    df=pd.concat([df, combine_customers_data_and_article_ID_1element(article_id_list,customers_metadata,i+1)])
df

0/954
1/954
2/954
3/954
4/954
5/954
6/954
7/954
8/954
9/954
10/954
11/954
12/954
13/954
14/954
15/954
16/954
17/954
18/954
19/954
20/954
21/954
22/954
23/954
24/954
25/954
26/954
27/954
28/954
29/954
30/954
31/954
32/954
33/954
34/954
35/954
36/954
37/954
38/954
39/954
40/954
41/954
42/954
43/954
44/954
45/954
46/954
47/954
48/954
49/954
50/954
51/954
52/954
53/954
54/954
55/954
56/954
57/954
58/954
59/954
60/954
61/954
62/954
63/954
64/954
65/954
66/954
67/954
68/954
69/954
70/954
71/954
72/954
73/954
74/954
75/954
76/954
77/954
78/954
79/954
80/954
81/954
82/954
83/954
84/954
85/954
86/954
87/954
88/954
89/954
90/954
91/954
92/954
93/954
94/954
95/954
96/954
97/954
98/954
99/954
100/954
101/954
102/954
103/954
104/954
105/954
106/954
107/954
108/954
109/954
110/954
111/954
112/954
113/954
114/954
115/954
116/954
117/954
118/954
119/954
120/954
121/954
122/954
123/954
124/954
125/954
126/954
127/954
128/954
129/954
130/954
131/954
132/954
133/954
134/954
135/954
136/954
137/954
138/954
139/954
140/954
141/954
142/954
143/954
144/954
145/954
146/954
147/954
148/954
149/954
150/954
151/954
152/954
153/954
154/954
155/954
156/954
157/954
158/954
159/954
160/954
161/954
162/954
163/954
164/954
165/954
166/954
167/954
168/954
169/954
170/954
171/954
172/954
173/954
174/954
175/954
176/954
177/954
178/954
179/954
180/954
181/954
182/954
183/954
184/954
185/954
186/954
187/954
188/954
189/954
190/954
191/954
192/954
193/954
194/954
195/954
196/954
197/954
198/954
199/954
200/954
201/954
202/954
203/954
204/954
205/954
206/954
207/954
208/954
209/954
210/954
211/954
212/954
213/954
214/954
215/954
216/954
217/954
218/954
219/954
220/954
221/954
222/954
223/954
224/954
225/954
226/954
227/954
228/954
229/954
230/954
231/954
232/954
233/954
234/954
235/954
236/954
237/954
238/954
239/954
240/954
241/954
242/954
243/954
244/954
245/954
246/954
247/954
248/954
249/954
250/954
251/954
252/954
253/954
254/954
255/954
256/954
257/954
258/954
259/954
260/954
261/954
262/954
263/954
264/954
265/954
266/954
267/954
268/954
269/954
270/954
271/954
272/954
273/954
274/954
275/954
276/954
277/954
278/954
279/954
280/954
281/954
282/954
283/954
284/954
285/954
286/954
287/954
288/954
289/954
290/954
291/954
292/954
293/954
294/954
295/954
296/954
297/954
298/954
299/954
300/954
301/954
302/954
303/954
304/954
305/954
306/954
307/954
308/954
309/954
310/954
311/954
312/954
313/954
314/954
315/954
316/954
317/954
318/954
319/954
320/954
321/954
322/954
323/954
324/954
325/954
326/954
327/954
328/954
329/954
330/954
331/954
332/954
333/954
334/954
335/954
336/954
337/954
338/954
339/954
340/954
341/954
342/954
343/954
344/954
345/954
346/954
347/954
348/954
349/954
350/954
351/954
352/954
353/954
354/954
355/954
356/954
357/954
358/954
359/954
360/954
361/954
362/954
363/954
364/954
365/954
366/954
367/954
368/954
369/954
370/954
371/954
372/954
373/954
374/954
375/954
376/954
377/954
378/954
379/954
380/954
381/954
382/954
383/954
384/954
385/954
386/954
387/954
388/954
389/954
390/954
391/954
392/954
393/954
394/954
395/954
396/954
397/954
398/954
399/954
400/954
401/954
402/954
403/954
404/954
405/954
406/954
407/954
408/954
409/954
410/954
411/954
412/954
413/954
414/954
415/954
416/954
417/954
418/954
419/954
420/954
421/954
422/954
423/954
424/954
425/954
426/954
427/954
428/954
429/954
430/954
431/954
432/954
433/954
434/954
435/954
436/954
437/954
438/954
439/954
440/954
441/954
442/954
443/954
444/954
445/954
446/954
447/954
448/954
449/954
450/954
451/954
452/954
453/954
454/954
455/954
456/954
457/954
458/954
459/954
460/954
461/954
462/954
463/954
464/954
465/954
466/954
467/954
468/954
469/954
470/954
471/954
472/954
473/954
474/954
475/954
476/954
477/954
478/954
479/954
480/954
481/954
482/954
483/954
484/954
485/954
486/954
487/954
488/954
489/954
490/954
491/954
492/954
493/954
494/954
495/954
496/954
497/954
498/954
499/954
500/954
501/954
502/954
503/954
504/954
505/954
506/954
507/954
508/954
509/954
510/954
511/954
512/954
513/954
514/954
515/954
516/954
517/954
518/954
519/954
520/954
521/954
522/954
523/954
524/954
525/954
526/954
527/954
528/954
529/954
530/954
531/954
532/954
533/954
534/954
535/954
536/954
537/954
538/954
539/954
540/954
541/954
542/954
543/954
544/954
545/954
546/954
547/954
548/954
549/954
550/954
551/954
552/954
553/954
554/954
555/954
556/954
557/954
558/954
559/954
560/954
561/954
562/954
563/954
564/954
565/954
566/954
567/954
568/954
569/954
570/954
571/954
572/954
573/954
574/954
575/954
576/954
577/954
578/954
579/954
580/954
581/954
582/954
583/954
584/954
585/954
586/954
587/954
588/954
589/954
590/954
591/954
592/954
593/954
594/954
595/954
596/954
597/954
598/954
599/954
600/954
601/954
602/954
603/954
604/954
605/954
606/954
607/954
608/954
609/954
610/954
611/954
612/954
613/954
614/954
615/954
616/954
617/954
618/954
619/954
620/954
621/954
622/954
623/954
624/954
625/954
626/954
627/954
628/954
629/954
630/954
631/954
632/954
633/954
634/954
635/954
636/954
637/954
638/954
639/954
640/954
641/954
642/954
643/954
644/954
645/954
646/954
647/954
648/954
649/954
650/954
651/954
652/954
653/954
654/954
655/954
656/954
657/954
658/954
659/954
660/954
661/954
662/954
663/954
664/954
665/954
666/954
667/954
668/954
669/954
670/954
671/954
672/954
673/954
674/954
675/954
676/954
677/954
678/954
679/954
680/954
681/954
682/954
683/954
684/954
685/954
686/954
687/954
688/954
689/954
690/954
691/954
692/954
693/954
694/954
695/954
696/954
697/954
698/954
699/954
700/954
701/954
702/954
703/954
704/954
705/954
706/954
707/954
708/954
709/954
710/954
711/954
712/954
713/954
714/954
715/954
716/954
717/954
718/954
719/954
720/954
721/954
722/954
723/954
724/954
725/954
726/954
727/954
728/954
729/954
730/954
731/954
732/954
733/954
734/954
735/954
736/954
737/954
738/954
739/954
740/954
741/954
742/954
743/954
744/954
745/954
746/954
747/954
748/954
749/954
750/954
751/954
752/954
753/954
754/954
755/954
756/954
757/954
758/954
759/954
760/954
761/954
762/954
763/954
764/954
765/954
766/954
767/954
768/954
769/954
770/954
771/954
772/954
773/954
774/954
775/954
776/954
777/954
778/954
779/954
780/954
781/954
782/954
783/954
784/954
785/954
786/954
787/954
788/954
789/954
790/954
791/954
792/954
793/954
794/954
795/954
796/954
797/954
798/954
799/954
800/954
801/954
802/954
803/954
804/954
805/954
806/954
807/954
808/954
809/954
810/954
811/954
812/954
813/954
814/954
815/954
816/954
817/954
818/954
819/954
820/954
821/954
822/954
823/954
824/954
825/954
826/954
827/954
828/954
829/954
830/954
831/954
832/954
833/954
834/954
835/954
836/954
837/954
838/954
839/954
840/954
841/954
842/954
843/954
844/954
845/954
846/954
847/954
848/954
849/954
850/954
851/954
852/954
853/954
854/954
855/954
856/954
857/954
858/954
859/954
860/954
861/954
862/954
863/954
864/954
865/954
866/954
867/954
868/954
869/954
870/954
871/954
872/954
873/954
874/954
875/954
876/954
877/954
878/954
879/954
880/954
881/954
882/954
883/954
884/954
885/954
886/954
887/954
888/954
889/954
890/954
891/954
892/954
893/954
894/954
895/954
896/954
897/954
898/954
899/954
900/954
901/954
902/954
903/954
904/954
905/954
906/954
907/954
908/954
909/954
910/954
911/954
912/954
913/954
914/954
915/954
916/954
917/954
918/954
919/954
920/954
921/954
922/954
923/954
924/954
925/954
926/954
927/954
928/954
929/954
930/954
931/954
932/954
933/954
934/954
935/954
936/954
937/954
938/954
939/954
940/954
941/954
942/954
943/954
944/954
945/954
946/954
947/954
948/954
949/954
950/954
951/954
952/954

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code,article_id
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,108775015
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...,108775015
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...,108775015
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...,108775015
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...,108775015
...,...,...,...,...,...,...,...,...
2603,007ceeca2e2d1004495d4c431e920c3767c73cf49ced6b...,1.0,1.0,ACTIVE,Regularly,29.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024
2604,007cef836c7fd63c598224a2873ae243f6065c83bdb091...,NaN,NaN,PRE-CREATE,NONE,33.0,c5b07cfda2153ae74da3675e684bb42d5bbf3fc1c4f7b6...,305775024
2605,007cf000001673796420ec741413625939de806a0a152e...,NaN,NaN,ACTIVE,NONE,34.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024
2606,007cf457355e709ba01cc15460370436ffe9c9307625d5...,1.0,1.0,ACTIVE,Regularly,23.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024
2607,007cf9ab204ddc3e5c69efd8b361a12906d3b085a53118...,1.0,1.0,ACTIVE,Regularly,24.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024

In [6]:
articles_customers_metadata=pd.merge(df,articles_metadata,how='left')

In [7]:
articles_customers_metadata

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code,article_id,product_code,prod_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,108775015,108775,Strap top,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...,108775015,108775,Strap top,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...,108775015,108775,Strap top,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...,108775015,108775,Strap top,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...,108775015,108775,Strap top,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2488027,007ceeca2e2d1004495d4c431e920c3767c73cf49ced6b...,1.0,1.0,ACTIVE,Regularly,29.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024,305775,Lurex tights SG,...,Kids Girl S&T,H,Children Sizes 92-140,4,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...
2488028,007cef836c7fd63c598224a2873ae243f6065c83bdb091...,NaN,NaN,PRE-CREATE,NONE,33.0,c5b07cfda2153ae74da3675e684bb42d5bbf3fc1c4f7b6...,305775024,305775,Lurex tights SG,...,Kids Girl S&T,H,Children Sizes 92-140,4,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...
2488029,007cf000001673796420ec741413625939de806a0a152e...,NaN,NaN,ACTIVE,NONE,34.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024,305775,Lurex tights SG,...,Kids Girl S&T,H,Children Sizes 92-140,4,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...
2488030,007cf457355e709ba01cc15460370436ffe9c9307625d5...,1.0,1.0,ACTIVE,Regularly,23.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024,305775,Lurex tights SG,...,Kids Girl S&T,H,Children Sizes 92-140,4,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...
2488031,007cf9ab204ddc3e5c69efd8b361a12906d3b085a53118...,1.0,1.0,ACTIVE,Regularly,24.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024,305775,Lurex tights SG,...,Kids Girl S&T,H,Children Sizes 92-140,4,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...

In [11]:
transactions_train30000

,Unnamed: 0,t_dat,customer_id,article_id,price,sales_channel_id
0,0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2
1,1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2
2,2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2
3,3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2
4,4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2
...,...,...,...,...,...,...
29995,29995,2018-09-20,9c7c06ea9c871d012e5fb0b1066b8b26def259a5c1f162...,610776022,0.007254,2
29996,29996,2018-09-20,9c7c06ea9c871d012e5fb0b1066b8b26def259a5c1f162...,554598012,0.014508,2
29997,29997,2018-09-20,9c8087c21ad290830b7325da98f0934af435288118e0a2...,672598002,0.022017,2
29998,29998,2018-09-20,9c8087c21ad290830b7325da98f0934af435288118e0a2...,672598001,0.022017,2
29999,29999,2018-09-20,9c8087c21ad290830b7325da98f0934af435288118e0a2...,615141002,0.025407,2

In [10]:
transactions_train30000['result']='buy'

,Unnamed: 0,t_dat,customer_id,article_id,price,sales_channel_id
0,0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2
10026,10026,2018-09-20,3681748607f3287d2c3a65e00bb5fb153de30e9becf158...,663713001,0.049475,2
14906,14906,2018-09-20,4ef5967ff17bf474bffebe5b16bd54878e1d4105f7b4ed...,663713001,0.050831,2
20662,20662,2018-09-20,6b7b10d2d47516c82a6f97332478dab748070f09693f09...,663713001,0.050831,1
26426,26426,2018-09-20,8ac137752bbe914aa4ae6ad007a9a0c5b67a1ab2b2d474...,663713001,0.050831,2
29778,29778,2018-09-20,9ba65efcb0c8e886c8066fc3a2e432a715489300ee44c7...,663713001,0.050831,1

In [12]:
articles_customers_transactions_metadata=pd.merge(articles_customers_metadata,transactions_train30000,how='left')

In [13]:
articles_customers_transactions_metadata

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code,article_id,product_code,prod_name,...,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc,Unnamed: 0,t_dat,price,sales_channel_id
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...,108775015,108775,Strap top,...,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.,NaN,NaN,NaN,NaN
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...,108775015,108775,Strap top,...,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.,NaN,NaN,NaN,NaN
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...,108775015,108775,Strap top,...,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.,NaN,NaN,NaN,NaN
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...,108775015,108775,Strap top,...,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.,NaN,NaN,NaN,NaN
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...,108775015,108775,Strap top,...,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2488028,007ceeca2e2d1004495d4c431e920c3767c73cf49ced6b...,1.0,1.0,ACTIVE,Regularly,29.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024,305775,Lurex tights SG,...,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...,NaN,NaN,NaN,NaN
2488029,007cef836c7fd63c598224a2873ae243f6065c83bdb091...,NaN,NaN,PRE-CREATE,NONE,33.0,c5b07cfda2153ae74da3675e684bb42d5bbf3fc1c4f7b6...,305775024,305775,Lurex tights SG,...,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...,NaN,NaN,NaN,NaN
2488030,007cf000001673796420ec741413625939de806a0a152e...,NaN,NaN,ACTIVE,NONE,34.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024,305775,Lurex tights SG,...,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...,NaN,NaN,NaN,NaN
2488031,007cf457355e709ba01cc15460370436ffe9c9307625d5...,1.0,1.0,ACTIVE,Regularly,23.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024,305775,Lurex tights SG,...,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...,NaN,NaN,NaN,NaN
2488032,007cf9ab204ddc3e5c69efd8b361a12906d3b085a53118...,1.0,1.0,ACTIVE,Regularly,24.0,2c29ae653a9282cce4151bd87643c907644e09541abc28...,305775024,305775,Lurex tights SG,...,Baby/Children,79,Girls Underwear & Basics,1021,Socks and Tights,Tights in a fine knit containing glittery thre...,NaN,NaN,NaN,NaN

In [15]:
articles_customers_transactions_metadata.columns.values.tolist()

['customer_id',
 'FN',
 'Active',
 'club_member_status',
 'fashion_news_frequency',
 'age',
 'postal_code',
 'article_id',
 'product_code',
 'prod_name',
 'product_type_no',
 'product_type_name',
 'product_group_name',
 'graphical_appearance_no',
 'graphical_appearance_name',
 'colour_group_code',
 'colour_group_name',
 'perceived_colour_value_id',
 'perceived_colour_value_name',
 'perceived_colour_master_id',
 'perceived_colour_master_name',
 'department_no',
 'department_name',
 'index_code',
 'index_name',
 'index_group_no',
 'index_group_name',
 'section_no',
 'section_name',
 'garment_group_no',
 'garment_group_name',
 'detail_desc',
 'Unnamed: 0',
 't_dat',
 'price',
 'sales_channel_id']

In [ ]:
df.drop(["B", "C"], axis=1)